Uknow\PlatformBundle\Entity\Donnees:
    type: entity
    table: null
    repositoryClass: Uknow\PlatformBundle\Entity\DonneesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        structure:
            type: string
            length: 12
        titre:
            type: string
            length: 40
        description:
            type: string
            length: 160
        texte:
            type: text
        correction:
            type: text
            nullable: true
        date:
            type: datetime
        pertinent:
            type: integer
        developper:
            type: integer
        inadequat:
            type: integer
        type:
            type: string
            length: 13
        niveau:
            type: string
            length: 10
        fiabilite:
            type: integer
        temps:
            type: integer
    lifecycleCallbacks: {  }